[build]
  base = "frontend"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_BACKEND_URL = "https://hd-monks-web-app.onrender.com"
